// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"fr_CH": &dictionary{index: fr_CHIndex, data: fr_CHData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d books available":   4,
	"%d books available\n": 1,
	"Launching soon!":      5,
	"Launching soon!\n":    2,
	"Welcome!":             3,
	"Welcome!\n":           0,
}

var en_GBIndex = []uint32{ // 7 elements
	0x00000000, 0x0000000e, 0x00000046, 0x0000005b,
	0x00000064, 0x00000097, 0x000000a7,
} // Size: 52 bytes

const en_GBData string = "" + // Size: 167 bytes
	"\x04\x00\x01\x0a\x09\x02Welcome!\x04\x00\x01\x0a3\x14\x01\x81\x01\x00=" +
	"\x01\x13\x02One book available\x00\x16\x02%[1]d books available\x04\x00" +
	"\x01\x0a\x10\x02Launching soon!\x02Welcome!\x14\x01\x81\x01\x00=\x01\x13" +
	"\x02One book available\x00\x16\x02%[1]d books available\x02Launching soo" +
	"n!"

var fr_CHIndex = []uint32{ // 7 elements
	0x00000000, 0x00000011, 0x0000004d, 0x00000068,
	0x00000074, 0x000000ab, 0x000000c1,
} // Size: 52 bytes

const fr_CHData string = "" + // Size: 193 bytes
	"\x04\x00\x01\x0a\x0c\x02Bienvenue !\x04\x00\x01\x0a7\x14\x01\x81\x01\x00" +
	"=\x01\x14\x02Un livre disponible\x00\x19\x02%[1]d livres disponibles\x04" +
	"\x00\x01\x0a\x16\x02Bientôt disponible !\x02Bienvenue !\x14\x01\x81\x01" +
	"\x00=\x01\x14\x02Un livre disponible\x00\x19\x02%[1]d livres disponibles" +
	"\x02Bientôt disponible !"

var zh_CNIndex = []uint32{ // 7 elements
	0x00000000, 0x0000000f, 0x0000004c, 0x00000061,
	0x0000006b, 0x000000a3, 0x000000b3,
} // Size: 52 bytes

const zh_CNData string = "" + // Size: 179 bytes
	"\x04\x00\x01\x0a\x0a\x02欢迎！\x04\x00\x01\x0a8\x14\x01\x81\x01\x00<\x03" +
	"\x17\x02仅 %[1]d 本书可用\x00\x17\x02共 %[1]d 本书可用\x04\x00\x01\x0a\x10\x02敬请期待" +
	"！\x02欢迎！\x14\x01\x81\x01\x00<\x03\x17\x02仅 %[1]d 本书可用\x00\x17\x02共 %[1" +
	"]d 本书可用\x02敬请期待！"

	// Total table size 695 bytes (0KiB); checksum: 5F78E193
